export const PERMISSIONS = {
  IAM_PERMISSION_READ: 'IAM.PERMISSION.READ',
  IAM_PERMISSION_MANAGE: 'IAM.PERMISSION.MANAGE',
  IAM_USER_READ: 'IAM.USER.READ',
  IAM_USER_CREATE: 'IAM.USER.CREATE',
  IAM_USER_UPDATE: 'IAM.USER.UPDATE',
  IAM_USER_DEACTIVATE: 'IAM.USER.DEACTIVATE',
  IAM_USER_RESET_PASSWORD: 'IAM.USER.RESET_PASSWORD',
  IAM_USER_MANAGE_ROLE: 'IAM.USER.MANAGE_ROLE',
  IAM_BRANCH_SCOPE_READ: 'IAM.BRANCH_SCOPE.READ',
  IAM_BRANCH_SCOPE_MANAGE: 'IAM.BRANCH_SCOPE.MANAGE',
  BRANCH_ACCESS_ALL: 'BRANCH.ACCESS_ALL',
  BRANCH_READ: 'BRANCH.READ',
  BRANCH_CREATE: 'BRANCH.CREATE',
  BRANCH_UPDATE: 'BRANCH.UPDATE',
  BRANCH_DELETE: 'BRANCH.DELETE',
  AUDIT_READ: 'AUDIT.READ',
  AUDIT_EXPORT: 'AUDIT.EXPORT',
  INVOICE_READ: 'INVOICE.READ',
  INVOICE_CREATE: 'INVOICE.CREATE',
  INVOICE_UPDATE: 'INVOICE.UPDATE',
  INVOICE_FINALIZE: 'INVOICE.FINALIZE',
  INVOICE_PAYMENT: 'INVOICE.PAYMENT',
  INVOICE_CANCEL: 'INVOICE.CANCEL',
  INVOICE_PROOF_READ: 'INVOICE.PROOF.READ',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

