'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ShoppingCart } from 'lucide-react';
import { cashBankApi, type CashBankAccount } from '@/lib/cashBankApi';
import { purchasingApi, type PurchaseOrder, type PurchaseRequest, type Supplier, type SupplierInvoice } from '@/lib/purchasingApi';
import { showToast } from '@/lib/toast';

export default function PurchasingPage() {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [requests, setRequests] = useState<PurchaseRequest[]>([]);
  const [orders, setOrders] = useState<PurchaseOrder[]>([]); const [invoices, setInvoices] = useState<SupplierInvoice[]>([]);
  const [cashAccounts, setCashAccounts] = useState<CashBankAccount[]>([]); const [tab, setTab] = useState<'PR' | 'PO' | 'AP' | 'SUPPLIER'>('PR'); const [loading, setLoading] = useState(true);
  const reload = async () => { setLoading(true); try { const [s, r, o, ap, cash] = await Promise.all([purchasingApi.suppliers(), purchasingApi.requests(), purchasingApi.orders(), purchasingApi.accountsPayable(), cashBankApi.listAccounts({ isActive: 'true' })]); setSuppliers(s); setRequests(r); setOrders(o); setInvoices(ap); setCashAccounts(cash); } catch (error: any) { showToast.error(error.response?.data?.error?.message || 'Gagal memuat purchasing.'); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, []);
  const act = async (fn: () => Promise<unknown>, message: string) => { try { await fn(); showToast.success(message); await reload(); } catch (error: any) { showToast.error(error.response?.data?.error?.message || 'Aksi gagal.'); } };
  return <div className="mx-auto max-w-7xl space-y-5"><header><h1 className="flex items-center gap-2 text-2xl font-semibold"><ShoppingCart /> Purchasing & Accounts Payable</h1><p className="mt-1 text-sm text-neutral-500">Alur auditabel PR → PO → Goods Receipt/GRNI → supplier invoice/AP → pembayaran kas/bank.</p></header>
    <div className="flex gap-2">{(['PR','PO','AP','SUPPLIER'] as const).map((value) => <button key={value} onClick={() => setTab(value)} className={`rounded-lg px-4 py-2 text-sm ${tab === value ? 'bg-blue-600 text-white' : 'border'}`}>{value === 'SUPPLIER' ? 'Supplier' : value}</button>)}</div>
    {loading ? <p>Memuat…</p> : <>{tab === 'PR' && <Table headers={['PR','Tanggal','Keterangan','Status','Aksi']}>{requests.map((row) => <tr key={row.id} className="border-t"><Cell><b>{row.requestNumber}</b></Cell><Cell>{date(row.requestDate)}</Cell><Cell>{row.description}<small className="block text-neutral-500">{row.items.length} item</small></Cell><Cell>{row.status}</Cell><Cell><div className="flex gap-2">{row.status === 'DRAFT' && <Small onClick={() => act(() => purchasingApi.submitRequest(row.id), 'PR diajukan.')}>Ajukan</Small>}{row.status === 'SUBMITTED' && <><Small onClick={() => act(() => purchasingApi.approveRequest(row), 'PR disetujui.')}>Approve semua</Small><Small onClick={() => { const reason = prompt('Alasan penolakan'); if (reason) void act(() => purchasingApi.rejectRequest(row.id, reason), 'PR ditolak.'); }}>Tolak</Small></>}{row.status === 'APPROVED' && <Small onClick={() => { const supplierId = promptSupplier(suppliers); if (supplierId) void act(() => purchasingApi.createOrder(row.id, supplierId), 'PO diterbitkan.'); }}>Buat PO</Small>}</div></Cell></tr>)}</Table>}
      {tab === 'PO' && <Table headers={['PO','Supplier','Status receipt','Nilai','Invoice']}>{orders.map((row) => <tr key={row.id} className="border-t"><Cell><b>{row.poNumber}</b><small className="block">{date(row.orderDate)}</small></Cell><Cell>{row.supplier.code} — {row.supplier.name}</Cell><Cell>{row.status}<small className="block text-neutral-500">{row.goodsReceipts.length} receipt</small></Cell><Cell>Rp {row.totalAmount}</Cell><Cell>{['PARTIALLY_RECEIVED','RECEIVED'].includes(row.status) && <Small onClick={() => { const number = prompt('Nomor invoice supplier'); const amount = prompt('Nominal invoice', row.totalAmount); if (number && amount) void act(() => purchasingApi.postInvoice(row.id, number, amount, row.supplier.paymentTermsDays), 'Supplier invoice diposting.'); }}>Post invoice</Small>}</Cell></tr>)}</Table>}
      {tab === 'AP' && <Table headers={['Invoice','Supplier / PO','Jatuh tempo','Saldo','Status / Aksi']}>{invoices.map((row) => <tr key={row.id} className="border-t"><Cell><b>{row.supplierInvoiceNumber}</b><small className="block">{row.journalEntry.journalNumber}</small></Cell><Cell>{row.supplier.name}<small className="block">{row.purchaseOrder.poNumber}</small></Cell><Cell>{date(row.dueDate)}</Cell><Cell>Rp {row.balanceAmount}<small className="block">dibayar Rp {row.paidAmount}</small></Cell><Cell>{row.status !== 'PAID' ? <Small onClick={() => { const accountId = promptCash(cashAccounts.filter((account) => account.branchId === row.branchId)); const amount = prompt('Nominal pembayaran', row.balanceAmount); const reference = prompt('Referensi pembayaran'); if (accountId && amount && reference) void act(() => purchasingApi.payInvoice(row.id, accountId, amount, reference), 'Pembayaran supplier diposting.'); }}>Bayar</Small> : 'PAID'}</Cell></tr>)}</Table>}
      {tab === 'SUPPLIER' && <><SupplierForm onSaved={reload} /><Table headers={['Kode','Nama','Termin','Status']}>{suppliers.map((row) => <tr key={row.id} className="border-t"><Cell>{row.code}</Cell><Cell>{row.name}</Cell><Cell>{row.paymentTermsDays} hari</Cell><Cell>{row.status}</Cell></tr>)}</Table></>}</>}
  </div>;
}

function SupplierForm({ onSaved }: { onSaved: () => Promise<void> }) { const [form, setForm] = useState({ code: '', name: '', paymentTermsDays: '30' }); const submit = async (event: FormEvent) => { event.preventDefault(); try { await purchasingApi.createSupplier({ ...form, paymentTermsDays: Number(form.paymentTermsDays) }); showToast.success('Supplier dibuat.'); setForm({ code: '', name: '', paymentTermsDays: '30' }); await onSaved(); } catch (error: any) { showToast.error(error.response?.data?.error?.message || 'Gagal membuat supplier.'); } }; return <form onSubmit={submit} className="mb-4 grid gap-3 rounded-xl border p-4 md:grid-cols-4"><input className="rounded-lg border bg-transparent px-3 py-2" required placeholder="Kode" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })}/><input className="rounded-lg border bg-transparent px-3 py-2" required placeholder="Nama supplier" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/><input className="rounded-lg border bg-transparent px-3 py-2" required type="number" min="0" placeholder="Termin hari" value={form.paymentTermsDays} onChange={(e) => setForm({ ...form, paymentTermsDays: e.target.value })}/><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Tambah supplier</button></form>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto rounded-xl border bg-white dark:bg-neutral-900"><table className="w-full text-sm"><thead><tr className="text-left">{headers.map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Cell({ children }: { children: React.ReactNode }) { return <td className="p-3 align-top">{children}</td>; } function Small({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button onClick={onClick} className="rounded border px-2 py-1 text-xs">{children}</button>; }
const date = (value: string) => new Date(value).toLocaleDateString('id-ID');
function promptSupplier(rows: Supplier[]) { const code = prompt(`Kode supplier:\n${rows.filter((r) => r.status === 'ACTIVE').map((r) => `${r.code} — ${r.name}`).join('\n')}`)?.toUpperCase(); return rows.find((row) => row.code === code)?.id; }
function promptCash(rows: CashBankAccount[]) { const code = prompt(`Kode kas/bank:\n${rows.map((r) => `${r.code} — ${r.name}`).join('\n')}`)?.toUpperCase(); return rows.find((row) => row.code === code)?.id; }
