'use client';

import { FormEvent, useEffect, useState } from 'react';
import { BadgeDollarSign } from 'lucide-react';
import { revenueApi, type PackagePricing, type RevenueContract, type RevenuePolicy, type TreatmentEvent } from '@/lib/revenueApi';
import { showToast } from '@/lib/toast';

export default function RevenueRecognitionPage() {
  const [policies, setPolicies] = useState<RevenuePolicy[]>([]); const [contracts, setContracts] = useState<RevenueContract[]>([]);
  const [events, setEvents] = useState<TreatmentEvent[]>([]); const [pricings, setPricings] = useState<PackagePricing[]>([]);
  const [tab, setTab] = useState<'CONTRACT' | 'EVENT' | 'POLICY'>('CONTRACT'); const [loading, setLoading] = useState(true);
  const reload = async () => { setLoading(true); try { const [p, c, e, pp] = await Promise.all([revenueApi.policies(), revenueApi.contracts(), revenueApi.events(), revenueApi.packagePricings()]); setPolicies(p); setContracts(c); setEvents(e); setPricings(pp.filter((row) => row.isActive)); } catch (error: any) { showToast.error(error.response?.data?.error?.message || 'Gagal memuat deferred revenue.'); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, []);
  return <div className="mx-auto max-w-7xl space-y-5"><header><h1 className="flex items-center gap-2 text-2xl font-semibold"><BadgeDollarSign /> Deferred Revenue</h1><p className="mt-1 text-sm text-neutral-500">Pembayaran paket tetap sebagai liabilitas; omzet baru disiapkan per sesi melalui event TREATMENT_COMPLETED.</p></header>
    <div className="flex gap-2">{(['CONTRACT','EVENT','POLICY'] as const).map((value) => <button key={value} onClick={() => setTab(value)} className={`rounded-lg px-4 py-2 text-sm ${tab === value ? 'bg-blue-600 text-white' : 'border'}`}>{value === 'CONTRACT' ? 'Kontrak' : value === 'EVENT' ? 'Event' : 'Policy'}</button>)}</div>
    {loading ? <p>Memuat…</p> : <>{tab === 'CONTRACT' && <Table heads={['Paket / Member','Consideration','Deferred funded','Recognized','Per sesi','Status']}>{contracts.map((row) => <tr className="border-t" key={row.id}><Cell><b>{row.memberPackage.packageCode}</b><small className="block text-neutral-500">{row.memberPackage.member.user.profile?.fullName || '-'}</small></Cell><Cell>Rp {row.totalConsideration}</Cell><Cell>Rp {row.fundedDeferredAmount}<small className="block">sisa Rp {row.remainingDeferredAmount}</small></Cell><Cell>Rp {row.recognizedAmount}<small className="block">{row.recognizedSessions}/{row.memberPackage.totalSessions} sesi</small></Cell><Cell>Rp {row.valuation.regularSessionRevenue}<small className="block">final Rp {row.valuation.finalSessionRevenue}</small></Cell><Cell>{row.status}</Cell></tr>)}</Table>}
      {tab === 'EVENT' && <Table heads={['Event','Sesi','Waktu','Paket','Recognition']}>{events.map((row) => <tr className="border-t" key={row.id}><Cell><b>{row.eventType}</b><small className="block">{row.status}</small></Cell><Cell>{row.payload.sessionCode}</Cell><Cell>{new Date(row.occurredAt).toLocaleString('id-ID')}</Cell><Cell>{row.payload.packageIds.length}</Cell><Cell>{row.recognitions.length ? row.recognitions.map((item) => `${item.status}: Rp ${item.amount}`).join(', ') : 'Belum diposting'}</Cell></tr>)}</Table>}
      {tab === 'POLICY' && <><PolicyForm pricings={pricings} onSaved={reload}/><Table heads={['Package pricing','Metode','Deferred account','Revenue account','Versi']}>{policies.map((row) => <tr className="border-t" key={row.id}><Cell><b>{row.packagePricing.productCode || row.packagePricing.name}</b><small className="block">{row.packagePricing.totalSessions} sesi</small></Cell><Cell>{row.recognitionMethod}</Cell><Cell>{row.deferredRevenueAccount.code}</Cell><Cell>{row.revenueAccount.code}</Cell><Cell>{row.version}</Cell></tr>)}</Table></>}</>}
  </div>;
}

function PolicyForm({ pricings, onSaved }: { pricings: PackagePricing[]; onSaved: () => Promise<void> }) { const [form, setForm] = useState({ packagePricingId: '', deferredRevenueAccountCode: '2200', revenueAccountCode: '4100' }); const submit = async (event: FormEvent) => { event.preventDefault(); try { await revenueApi.savePolicy(form); showToast.success('Revenue policy disimpan.'); await onSaved(); } catch (error: any) { showToast.error(error.response?.data?.error?.message || 'Gagal menyimpan policy.'); } }; return <form onSubmit={submit} className="mb-4 grid gap-3 rounded-xl border p-4 md:grid-cols-4"><select required className="rounded-lg border bg-transparent px-3 py-2" value={form.packagePricingId} onChange={(e) => setForm({ ...form, packagePricingId: e.target.value })}><option value="">Pilih package pricing</option>{pricings.map((row) => <option key={row.id} value={row.id}>{row.productCode || row.name} — {row.totalSessions} sesi</option>)}</select><input required className="rounded-lg border bg-transparent px-3 py-2" aria-label="Deferred account" value={form.deferredRevenueAccountCode} onChange={(e) => setForm({ ...form, deferredRevenueAccountCode: e.target.value })} /><input required className="rounded-lg border bg-transparent px-3 py-2" aria-label="Revenue account" value={form.revenueAccountCode} onChange={(e) => setForm({ ...form, revenueAccountCode: e.target.value })} /><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Simpan policy</button></form>; }
function Table({ heads, children }: { heads: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto rounded-xl border bg-white dark:bg-neutral-900"><table className="w-full text-sm"><thead><tr className="text-left">{heads.map((head) => <th className="p-3" key={head}>{head}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; } function Cell({ children }: { children: React.ReactNode }) { return <td className="p-3 align-top">{children}</td>; }
