import { Router } from 'express';
import { authenticate } from '@middleware/authenticate';
import { requirePermission } from '@middleware/requirePermission';
import { PERMISSIONS } from '@modules/iam/permission-catalog';
import * as controller from './zoho.controller';

const router = Router();
router.get('/callback', controller.callback);
router.post('/webhooks/:organizationId', controller.receiveWebhook);
router.use(authenticate);
router.get('/status', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.status);
router.get('/events', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.events);
router.get('/events/:id', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.event);
router.post('/events/:id/retry', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.retryEvent);
router.post('/events/:id/ignore', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.ignoreEvent);
router.get('/discovery', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.discovery);
router.post('/discovery/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.runDiscovery);
router.post('/setup', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.setup);
router.get('/contacts', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.contacts);
router.get('/contacts/:entityType/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewContact);
router.post('/contacts/:entityType/:id/match', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.matchContact);
router.post('/contacts/:entityType/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueContact);
router.post('/contacts/reviews/:id/approve', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.approveContactReview);
router.post('/contacts/reviews/:id/reject', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.rejectContactReview);
router.get('/masters', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.masters);
router.get('/masters/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.masterConfig);
router.put('/masters/config/account', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapItemAccount);
router.put('/masters/config/uom', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapUom);
router.get('/masters/:entityType/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewMaster);
router.post('/masters/:entityType/:id/match', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.matchMaster);
router.post('/masters/:entityType/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueMaster);
router.post('/masters/reviews/:id/approve', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.approveMasterReview);
router.post('/masters/reviews/:id/reject', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.rejectMasterReview);
router.get('/invoices', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.invoices);
router.get('/invoices/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.invoiceConfig);
router.put('/invoices/config/tax', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapInvoiceTax);
router.get('/invoices/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewInvoice);
router.post('/invoices/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueInvoice);
router.get('/payments', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.payments);
router.get('/payments/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.paymentConfig);
router.put('/payments/config/account', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapPaymentAccount);
router.put('/payments/config/method', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapPaymentMethod);
router.get('/payments/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewPayment);
router.post('/payments/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueuePayment);
router.post('/payments/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcilePayments);
router.get('/retainers', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.retainers);
router.get('/retainers/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.retainerConfig);
router.put('/retainers/config/account', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapRetainerAccount);
router.post('/retainers/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcileRetainers);
router.get('/expenses', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.expenses);
router.get('/expenses/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.expenseConfig);
router.put('/expenses/config/account', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapExpenseAccount);
router.put('/expenses/config/paid-through', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapExpensePaidThrough);
router.get('/expenses/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewExpense);
router.post('/expenses/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueExpense);
router.post('/expenses/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcileExpenses);
router.get('/partnership-sales', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.partnershipSales);
router.get('/partnership-sales/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewPartnershipSale);
router.post('/partnership-sales/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueuePartnershipSale);
router.post('/partnership-sales/customers/:branchId/enqueue', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.enqueuePartnershipCustomer);
router.post('/partnership-sales/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcilePartnershipSales);
router.get('/purchase-orders', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.purchaseOrders);
router.post('/purchase-orders/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcilePurchaseOrders);
router.get('/purchase-orders/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewPurchaseOrder);
router.post('/purchase-orders/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueuePurchaseOrder);
router.post('/purchase-orders/:id/dependencies/enqueue', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.enqueuePurchaseOrderDependencies);
router.get('/bills', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.bills);
router.get('/grni', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.grni);
router.post('/bills/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcileBills);
router.get('/bills/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewBill);
router.post('/bills/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueBill);
router.post('/bills/:id/dependencies/enqueue', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.enqueueBillDependencies);
router.get('/vendor-payments', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.vendorPayments);
router.get('/vendor-payments/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.vendorPaymentConfig);
router.post('/vendor-payments/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcileVendorPayments);
router.get('/vendor-payments/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewVendorPayment);
router.post('/vendor-payments/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueVendorPayment);
router.get('/inventory-adjustments', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.inventoryAdjustments);
router.get('/inventory-adjustments/capability', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.inventoryAdjustmentCapability);
router.post('/inventory-adjustments/capability/probe', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.probeInventoryAdjustmentCapability);
router.get('/inventory-adjustments/export', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.exportInventoryAdjustments);
router.post('/inventory-adjustments/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcileInventoryAdjustments);
router.get('/webhooks', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.webhookInbox);
router.post('/webhooks/:id/correlate', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.retryWebhookCorrelation);
router.get('/reconciliation/runs', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.reconciliationRuns);
router.post('/reconciliation/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.runFullReconciliation);
router.post('/reconciliation/results/:id/resolve', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.resolveReconciliationException);
router.get('/go-live', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.goLiveControl);
router.put('/go-live', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.configureGoLive);
router.post('/go-live/mode', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.setGoLiveMode);
router.post('/go-live/approve', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.approveGoLive);
router.post('/go-live/rollback', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.rollbackGoLive);
router.post('/go-live/canary-day', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.recordCanaryDay);
router.get('/connect', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.connect);
router.post('/test', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.test);
router.post('/organizations/:id/activate', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.activate);
router.delete('/connection', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.disconnect);
export default router;
