import { Router } from 'express';
import { authenticate } from '@middleware/authenticate';
import { requirePermission } from '@middleware/requirePermission';
import { PERMISSIONS } from '@modules/iam/permission-catalog';
import * as controller from './zoho.controller';

const router = Router();
router.get('/callback', controller.callback);
router.use(authenticate);
router.get('/status', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.status);
router.get('/events', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.events);
router.get('/events/:id', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.event);
router.post('/events/:id/retry', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.retryEvent);
router.post('/events/:id/ignore', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.ignoreEvent);
router.get('/discovery', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.discovery);
router.post('/discovery/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.runDiscovery);
router.get('/contacts', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.contacts);
router.get('/contacts/:entityType/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewContact);
router.post('/contacts/:entityType/:id/match', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.matchContact);
router.post('/contacts/:entityType/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueContact);
router.post('/contacts/reviews/:id/approve', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.approveContactReview);
router.post('/contacts/reviews/:id/reject', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.rejectContactReview);
router.get('/masters', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.masters);
router.get('/masters/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.masterConfig);
router.put('/masters/config/account', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapItemAccount);
router.put('/masters/config/uom', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapUom);
router.get('/masters/:entityType/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewMaster);
router.post('/masters/:entityType/:id/match', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.matchMaster);
router.post('/masters/:entityType/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueMaster);
router.post('/masters/reviews/:id/approve', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.approveMasterReview);
router.post('/masters/reviews/:id/reject', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.rejectMasterReview);
router.get('/invoices', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.invoices);
router.get('/invoices/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.invoiceConfig);
router.put('/invoices/config/tax', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapInvoiceTax);
router.get('/invoices/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewInvoice);
router.post('/invoices/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueInvoice);
router.get('/payments', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.payments);
router.get('/payments/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.paymentConfig);
router.put('/payments/config/account', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapPaymentAccount);
router.put('/payments/config/method', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapPaymentMethod);
router.get('/payments/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewPayment);
router.post('/payments/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueuePayment);
router.post('/payments/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcilePayments);
router.get('/retainers', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.retainers);
router.get('/retainers/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.retainerConfig);
router.put('/retainers/config/account', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapRetainerAccount);
router.post('/retainers/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcileRetainers);
router.get('/expenses', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.expenses);
router.get('/expenses/config', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.expenseConfig);
router.put('/expenses/config/account', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapExpenseAccount);
router.put('/expenses/config/paid-through', requirePermission(PERMISSIONS.ZOHO_MAPPING_MANAGE), controller.mapExpensePaidThrough);
router.get('/expenses/:id/preview', requirePermission(PERMISSIONS.ZOHO_SYNC_READ), controller.previewExpense);
router.post('/expenses/:id/enqueue', requirePermission(PERMISSIONS.ZOHO_SYNC_RETRY), controller.enqueueExpense);
router.post('/expenses/reconcile/run', requirePermission(PERMISSIONS.ZOHO_RECONCILE_RUN), controller.reconcileExpenses);
router.get('/connect', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.connect);
router.post('/test', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.test);
router.post('/organizations/:id/activate', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.activate);
router.delete('/connection', requirePermission(PERMISSIONS.ZOHO_CONNECTION_MANAGE), controller.disconnect);
export default router;
