ALTER TYPE "DiagnosisCategory" ADD VALUE IF NOT EXISTS 'STROKE';
ALTER TYPE "DiagnosisCategory" ADD VALUE IF NOT EXISTS 'JANTUNG_KARDIOVASKULAR';
ALTER TYPE "DiagnosisCategory" ADD VALUE IF NOT EXISTS 'SINDROM_METABOLIK';
ALTER TYPE "DiagnosisCategory" ADD VALUE IF NOT EXISTS 'KANKER';
ALTER TYPE "DiagnosisCategory" ADD VALUE IF NOT EXISTS 'DEGENERATIF';
ALTER TYPE "DiagnosisCategory" ADD VALUE IF NOT EXISTS 'AUTO_IMUN';
