/**
 * Transitional DTO for inventory screens that combine several reporting
 * endpoints in one page. Named fields keep rendering type-safe while the
 * unknown index preserves forward-compatible API metadata.
 */
export interface InventoryLegacyRow {
  [key: string]: unknown;
  id: string;
  code?: string;
  name?: string;
  sku?: string;
  label?: string;
  branchCode?: string;
  branchName?: string;
  category?: string;
  type?: string;
  status?: string;
  unit?: string;
  baseUnit?: string;
  usageUnit?: string;
  batchNumber?: string;
  postingNumber?: string;
  poNumber?: string;
  adjustmentNumber?: string;
  opnameNumber?: string;
  receiptNumber?: string;
  requestCode?: string;
  reasonCode?: string;
  description?: string;
  notes?: string;
  direction?: string;
  currency?: string;
  createdAt?: string;
  updatedAt?: string;
  receivedAt?: string;
  postedAt?: string;
  occurredAt?: string;
  snapshotAt?: string;
  manufactureDate?: string | null;
  expiryDate?: string | null;
  isActive?: boolean;
  isDefault?: boolean;
  isLowStock?: boolean;
  tracksBatch?: boolean;
  tracksExpiry?: boolean;
  isBlocked?: boolean;
  quantityReconciled?: boolean;
  quantity?: number;
  quarantine?: number;
  value?: number;
  stock?: number;
  onHand?: number;
  available?: number;
  reserved?: number;
  quarantineQuantity?: number;
  inTransit?: number;
  totalValue?: number;
  minThreshold?: number;
  precision?: number;
  conversionFactor?: number;
  baseUomId?: string;
  usageUomId?: string;
  physicalQty?: string;
  systemQty?: string;
  resolvedUnitCost?: string;
  systemUnitCost?: string;
  resolutionNote?: string;
  unitCost?: string | number;
  totalEstimatedValue?: string | number;
  totalQuantity?: string | number;
  quarantinedQuantity?: string | number;
  totalCost?: string | number;
  orderedQty?: string | number;
  receivedQty?: string | number;
  remainingQty?: string | number;
  approvedQty?: string | number;
  requestedQty?: string | number;
  finalQty?: string | number;
  onHandQty?: string | number;
  availableQty?: string | number;
  reservedQty?: string | number;
  quarantineQty?: string | number;
  inTransitQty?: string | number;
  originalQty?: string | number;
  actualCost?: string | number;
  inboundQty?: string | number;
  outboundQty?: string | number;
  runningQty?: string | number;
  averageUnitCost?: string | number;
  inventoryValue?: string | number;
  layerValue?: string | number;
  inTransitValue?: string | number;
  totalInventoryValue?: string | number;
  mismatchCount?: number;
  inventoryItemId?: string;
  masterProductId?: string;
  batchId?: string;
  branchId?: string;
  purchaseOrderItemId?: string;
  stockRequestId?: string;
  sourceId?: string;
  sourceType?: string;
  referenceId?: string;
  referenceType?: string;
  productName?: string;
  condition?: string;
  masterProduct?: InventoryLegacyRow;
  branch?: InventoryLegacyRow;
  purchaseOrder?: InventoryLegacyRow;
  stockRequest?: InventoryLegacyRow;
  stockRequestItem?: InventoryLegacyRow;
  inventoryBalance?: InventoryLegacyRow;
  inventoryPosting?: InventoryLegacyRow;
  inventoryItem?: InventoryLegacyRow;
  stockLocation?: InventoryLegacyRow;
  baseUom?: InventoryLegacyRow;
  usageUom?: InventoryLegacyRow;
  supplier?: InventoryLegacyRow;
  batch?: InventoryLegacyRow | null;
  lines?: InventoryLegacyRow[];
  items?: InventoryLegacyRow[];
  batches?: InventoryLegacyRow[];
  costLayers?: InventoryLegacyRow[];
  stockMutations?: InventoryLegacyRow[];
}
